default_direction:
  default: horizontal
  type: enum
  choices:
    - horizontal
    - vertical
add_images_prompt:
  default: "*Add two images here.* Change 'data-direction-horizontal' to 'data-direction-vertical' for a vertical slider."
button_icon:
  default: "bolt"
button_text:
  default: "Image comparison slider"