default_direction:
  default: horizontal
  type: enum
  choices:
    - horizontal
    - vertical
add_images_prompt:
  default: "Add two images"
button_icon:
  default: "bolt"
button_text:
  default: "Image Comparison Slider"