default_direction:
  default: horizontal
  type: enum
  choices:
    - horizontal
    - vertical
add_images_prompt:
  default: "Add two or more images here. Use 'data-direction-vertical' for a vertical slider."
button_icon:
  default: "bolt"
button_text:
  default: "Image comparison slider"
handle_arrow_style:
  type: enum
  default: line
  choices:
    - line
    - solid
max_images:
  default: 5
  type: integer
  min: 2
  max: 10