default_direction:
  default: horizontal
  type: enum
  choices:
    - horizontal
    - vertical
add_images_prompt:
  default: "在此添加两张图片。将 'data-direction-horizontal' 改为 'data-direction-vertical' 可切换为垂直滑块。"
button_icon:
  default: "bolt"
button_text:
  default: "图片对比滑块"
handle_arrow_style:
  type: enum
  default: line
  choices:
    - line
    - solid